civilproblem/civilproblem/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    path('',include('main.urls')),
    path('about',views.about,name='about')
    


    # path('userlogin',views.userlogin,name='userlogin'),
    # path('adminlogin',views.adminlogin,name='adminlogin'),
    # path('register',views.register,name='register'),
    #path('registernew',views.registernew,name='registernew')
    
]

civilproblem/main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'civilproblem_main'
urlpatterns = [
    path('adminlogin',views.adminlogin,name='adminlogin'),
     
    path('notsolved',views.notsolved,name='views.notsolved'),
    path('progress',views.progress,name='views.progress'),
    path('complete',views.complete,name='views.complete'),
    path('view',views.view,name='views.view'),
    path('welcome',views.welcome,name='views.welcome'),
    path('nur',views.nur,name='nur'),
    path('addprob',views.addprob,name='views.addprob'),
    path('feedback/<int:id>',views.Feedback,name="views.Feedback"),
    path('feedback/fsubmit/<int:id>/',views.fsubmit,name='fsubmit'),
    path('schedule/<int:id>',views.schedule,name='views.schedule'),
    path('delete/<int:id>',views.delete,name='views.delete'),
    path('modify/<int:id>',views.modify,name='views.modify'),
    path('adminlogout',views.adminlogout,name='views.adminlogout'),
    path('searchproblem',views.searchproblem,name='views.searchproblem'),
    path('startworking/<int:id>',views.startworking,name='startworking')

    

    
    
]

civilproblem/main/models.py
from django.db import models
from datetime import datetime,date

# Create your models here.
class problems(models.Model):
    COMPLETED = 'CC'
    PENDING = 'IC'
    PROGRESS= 'IP'
    CHOICES = [
        (COMPLETED, 'CC'),
        (PENDING, 'IC'),
        (PROGRESS, 'IP'),]
    prob_id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=50)
    desc=models.CharField(max_length=5000)
    
    postedby=models.CharField(max_length=50)
    location=models.CharField(max_length=50, default="")
    votes=models.IntegerField()
    status=models.CharField(
        max_length=2,
        choices=CHOICES,
        default=COMPLETED,
    )
    postdate=models.DateField("postdate(mm/dd/yyyy)",auto_now_add=False,auto_now=False,blank=True)
    startdate=models.DateField("startdate(mm/dd/yyyy)",auto_now_add=False,auto_now=False,blank=True,null=True)
    ecompletiondate=models.DateField("ecompletiondate(mm/dd/yyyy)",auto_now_add=False,auto_now=False,blank=True,null=True)
    acompletiondate=models.DateField("acompletiondate(mm/dd/yyyy)",auto_now_add=False,auto_now=False,blank=True,null=True)
    def __str__(self):
        return self.title
class feedback(models.Model):
    myfeedback=models.CharField(max_length=50000)
    
    prob_id=models.ForeignKey(problems,on_delete=models.CASCADE)










    
    
    




    




civilproblem/main/forms.py
from socket import fromshare
from django import forms
from django.forms import ModelForm
from .models import problems
#create problem form lfor adding problems to the databse from the user side 
class problemform(ModelForm):
    class Meta:
        model=problems
        fields="__all__"


civilproblem/main/views.py
from django.shortcuts import HttpResponse, redirect, render

from .models import problems,feedback
from .forms import problemform
from django.http import HttpResponseRedirect
from user.models import myuser
from django.db.models import Q

# Create your views here.
def adminlogin(request):
     return render(request,'adminlogin.html')

def adminlogout(request):
     return redirect('/')
def notsolved(request):
     problem=problems.objects.all()
     context={
        'problems':problem
    }
    #print(context)
    #return render(request,'viewbooks.html',context)
     #return render(request,'view.html',context)
     return render(request,'ns.html',context)
def progress(request):
     problem=problems.objects.all()
     context={
        'problems':problem
    }
     return render(request,'ip.html',context)
def complete(request):
     problem=problems.objects.all()
     context={
        'problems':problem
    }
    #print(context)
    #return render(request,'viewbooks.html',context)
     #return render(request,'view.html',context)
     #return render(request,'ns.html',context)
     return render(request,'c.html',context)
def searchproblem(request):
     if request.method=="POST":
          searched=request.POST['searched']
          print(searched)
          problem=problems.objects.all()
          if problem:
               problem=problems.objects.filter(Q(title__icontains=searched))
          context={
            'problems':problem
          }

             
     return render(request,'main/templates/view.html',context)
def view(request):
     problem=problems.objects.all()
     context={
        'problems':problem
    }
    #print(context)
    #return render(request,'viewbooks.html',context)
     return render(request,'view.html',context)
def welcome(request):
     return render(request,'welcome.html')
def nur(request):
     return render(request,'nur.html')
def addprob(request):
     submitted=False
     if request.method=='POST':
          form=problemform(request.POST)
          if form.is_valid():
               form.save()
               return HttpResponseRedirect('addprob?submitted=True')
     else:
          form=problemform
          if 'submitted' in request.GET:
               submitted=True

          
     return render(request,'addprob.html',{'form':form ,'submitted':submitted})
def Feedback(request,id=0):
     problem=problems.objects.get(prob_id=id)
     #form=bookform(request.POST or None,instance=modify)
     #if form.is_valid():
        #form.save()
        #return redirect('viewbooks')
     context={
          'problem':problem
     }
     return render(request,'feedback.html',context)

#      all=problems.objects.all()
#      context={
#         'problems':problems,
#         #'form':form
        
#     }
#      return render(request,'updatebook.html',context)
def fsubmit(request, id):
     # Get the problem with the id passed to the view
     myid= problems.objects.get(pk=id)
     context = {'problem': myid}
     if request.method=='POST':
          feedbackk=request.POST['feedback']          
          newfeedback=feedback(myfeedback=feedbackk ,prob_id=myid)
          newfeedback.save()
          return HttpResponse('Submitted Succesfully .Thankyou for your feedback!!')
     return render(request,'feedback.html', context= context)
def schedule(request,id=0):
     problem=problems.objects.get(prob_id=id)
     context={
          'problem':problem
     }
     return render(request,'schedule.html',context)
def delete (request ,id=0):
     if id:
        try:
            remove=problems.objects.get(prob_id=id)
            remove.delete()
            #return HttpResponse('Deleted Succesfully.please refresh the page ')
            return redirect('/view')

        except:
            return HttpResponse('enable to delete please try again later ')

#      problem=problems.objects.all()
#      context={
#         'problems':problem
#     }
#      return render(request,'view.html',context)
def modify(request,id):
     modify=problems.objects.get(pk=id)
     form=problemform(request.POST or None,instance=modify )
     if form.is_valid():
          form.save()
          return redirect('/view')

     problem=problems.objects.all()
     context={
        'problems':problem,
        'form':form
    }
     return render(request,'update.html',context)

def adminlogin(request):
     if request.method=='POST':
          
          username=request.POST['username']
          password=request.POST['password']
          user=myuser.objects.filter(username=username,password=password)
          if request.user.is_superuser:
               return redirect('welcome')
     return render(request,'adminlogin.html')
def startworking(request,id):

     print(id)
     new=problems.objects.get(pk=id)
     if request.method=='POST':
          estdate=request.POST['ed']
          print(estdate)
          startdate=request.POST['sd']
          print(startdate)
          new.ecompletiondate=estdate
          new.startdate=startdate
          print("hello")

          new.save()
          print("saved")
     else:
          print("in else loop rn ")
          
     context={'problem':new}
     return render (request,'startworking.html',context)




     
          
     



civilproblem/main/templates/addprob.html
{% extends 'base.html' %}

{% block title%} ADD PROBLEM {% endblock %}
{% block body %}
<h3 >
ADD A NEW PROBLEM 

</h3>
{% if submitted %}
    added succesfully
{% else %}

    <form  action ="" method="POST">
        {% csrf_token %}

        {{form.as_p}}
        <button type="submit" class ="btn btn-primary">ADD </button>

    </form>
{% endif %}


{% endblock %}

civilproblem/main/templates/adminlogin.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>admin login</title>
  </head>
  <body>
    <h1>Welcome</h1>
    <p>Please Log in to get acesss to admin facilities</p>
    <div>
      {% csrf_token %}
        <form method="post" action ="adminlogin">
          <div class="form-group"></div>
            <label for="username">Username</label>
            <input type="text" name="username"class="form-control" id="username" aria-describedby="emailHelp" placeholder="Enter username">
            
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
          </div>
          
          <button type="submit" class="btn btn-primary">Login</button>
        </form>
      </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

civilproblem/main/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title%} {% endblock %}</title>
     <style>
      {% block css %} {% endblock %}
  </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Civil Problem Resolution</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="welcome">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="nur">New user request</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  View problem
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/notsolved">Problem not started</a></li>
                  <li><a class="dropdown-item" href="/progress">Problem in progress</a></li>
                  
                  <li><a class="dropdown-item" href="/complete">Problem solved</a></li>
                  <li><a class="dropdown-item" href="view">View all problems</a></li>
                </ul>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="addprob">Add problem</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="adminlogout">Log out</a>
              </li>
              
              
            </ul>
            
          </div>
        </div>
      </nav>
      <form method="POST" action="searchproblem">
        {% csrf_token%}
        <input type="text" placeholder="Search in all problems " name="searched">
      
      <button class="btn btn-primary">SEARCH</button>
    </form>
      <div>

        <table class="table table-light">
            
            <thead>
              <tr>
                <th scope="col">{% block th1 %}</th>{%endblock %}
                <th scope="col">{% block th2 %}</th>{%endblock %}
                <th scope="col">{% block th3 %}</th>{%endblock %}
                <th scope="col">{% block th4 %}</th>{%endblock %}
                <th scope="col">{% block th5 %}</th>{%endblock %}
                <th scope="col">{% block th6 %}</th>{%endblock %}
                <th scope="col">{% block th7 %}</th>{%endblock %}
                <th scope="col">{% block th8 %}</th>{%endblock %}


              </tr>
            </thead>
            <tbody>
                {% block mytablebody %} 
              
              
              
            </tbody>
            {% endblock %}
          </table>
      </div>
      
      {% block body %} {% endblock %}

    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    {% block js %} {% endblock %}
  </body>
</html>

civilproblem/main/templates/c.html
{% extends 'base.html' %}

{% block th1 %}Title{%endblock %}
{% block th2 %}description{%endblock %}
{% block th3 %} Post Date{%endblock %}
{% block th4 %}Posted by{%endblock %}
{% block th5 %}Location{%endblock %}
{% block th6 %}votes{%endblock %}

{% block th7 %}status{%endblock %}
{% block th8%}Date scheduling and feedback
{%endblock %}
{% block mytablebody %} 

    {% for i in problems  %}
    {%if  i.status in 'CC' %}
    

        <tr>
            <th scope="row">{{i.title}}</th>
            <td>{{i.desc}}</td>
            <td>{{i.postdate}}</td>
            <td>{{i.postedby}}</td>
            <td>{{i.location}}</td>
            <td>{{i.votes}}</td>
            
            <td >completed</td>
            <td>
                <a href="/schedule/{{i.prob_id}}">Date Schedule</a><br>
            
                <a  href="/feedback/{{i.prob_id}}">SEND FEEDBACK</a>
                
        </td> 
            
            

        </tr>
        {% endif %}
    {% endfor %}
{% endblock %}







civilproblem/main/templates/feedback.html
{% extends 'base.html' %}
{% block body %}
<form method="post" action="{% url 'civilproblem_main:fsubmit' id=problem.prob_id %}">
    {% csrf_token %}
    <h3>Enter the feedback for {{problem.prob_id}} with title as {{problem.title}}</h3>

    <textarea name="feedback" id="feedback" row="1000" cols="100">

        
5
    </textarea>
    <button type="submit" class ="btn btn-primary">SUBMIT</button>


</form>
{% endblock %}

civilproblem/main/templates/ip.html
{% extends 'base.html' %}

{% block th1 %}problem title{%endblock %}
{% block th2 %}description{%endblock %}
{% block th3 %} post date{%endblock %}
{% block th4 %}posted by{%endblock %}
{% block th5 %}location{%endblock %}
{% block th6 %}votes{%endblock %}
{% block th7 %}status{%endblock %}
{% block th8 %}DATE SCHEDULE {%endblock %}
{% block mytablebody %} 

    {% for i in problems  %}
    {% if  i.status in 'IP' %}
    

        <tr>
            <th scope="row">{{i.title}}</th>
            <td>{{i.desc}}</td>
            <td>{{i.postdate}}</td>
            <td>{{i.postedby}}</td>
            <td>{{i.location}}</td>
            <td>{{i.votes}}</td>
            
            <td >Progress</td>
            <td>                <a href="/schedule/{{i.prob_id}}">Date Schedule</a><br>
            </td>

            

        </tr>
        {% endif %}
    {% endfor %}
{% endblock %}

civilproblem/main/templates/ns.html
{% extends 'base.html' %}

{% block th1 %}problem title{%endblock %}
{% block th2 %}description{%endblock %}
{% block th3 %} post date{%endblock %}
{% block th4 %}posted by{%endblock %}
{% block th5 %}location{%endblock %}
{% block th6 %}votes{%endblock %}
{% block th7 %}status{%endblock %}
{% block th8 %}start working {%endblock %}
{% block mytablebody %} 

    {% for i in problems  %}
    {%if  i.status in 'IC' %}
    

        <tr>
            <th scope="row">{{i.title}}</th>
            <td>{{i.desc}}</td>
            <td>{{i.postdate}}</td>
            <td>{{i.postedby}}</td>
            <td>{{i.location}}</td>
            <td>{{i.votes}}</td>
            
            <td >Pending</td>
            <td><!-- Button trigger modal -->
                <a href="startworking/{{i.prob_id}}"><button type="button" class="btn btn-primary" data-mdb-toggle="modal" data-mdb-target="#exampleModal">
                  START WORKING
                </button></a>
                
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">...</div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                      </div>
                    </div>
                  </div>
                </div></td>

            

        </tr>
        {% endif %}
    {% endfor %}
{% endblock %}

civilproblem/main/templates/nur.html
{% extends 'base.html' %}
{% block body %}



<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">ADHAAR</th>
        <th scope="col">username</th>
        <th scope="col">email</th>
        <th scope="col">city</th>
        <th scope="col">address</th>
        <th scope="col">contact</th>
        <th scope="col">status</th>
        <th scope="col">assign</th>
        
        
        
        
        
      </tr>
    </thead>
    <tbody>
      
      
    </tbody>
  </table>
  {% endblock %}

civilproblem/main/templates/schedule.html
{% extends 'base.html' %}
{% block body %}
    
    
    
        <h3>{{problem.title}}</h3>
        <ul>
            <li> the estimate completion date :{{problem.ecompletiondate }}</li>
            {%if problem.acompletiondate not in 'None'%}
            <li> the actual completion date :{{problem.acompletiondate }}</li>
            {%else %}
            <li>the actual completion date will soon be assigned </li>
            {% endif %}
            
            
        </ul>
    
{% endblock %}

civilproblem/main/templates/startworking.html
{% extends 'base.html' %}
{% block body %}
<div class="card" style="width: 18rem;">
  
    
    <div class="card-body">
      <h5 class="card-title">{{problem.title}}</h5>
    {% csrf_token %}
      <form method="POST",action="startworking">
        <div class="form-group">
          <label for="sd"><b>ENTER START DATE </b></label>
          <input type="date" class="form-control" name="sd" id="sd" aria-describedby="emailHelp" placeholder="Enter start date ">
          
        </div>
        <div class="form-group">
            <label for="ed"><b>ENTER ESTIMATION DATE </b></label>
            <input type="date" class="form-control" name="ed" id="ed" aria-describedby="emailHelp" placeholder="Enter estimation date ">
            
          </div>
         
         
        
        <button type="submit" class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>


{%endblock%}

civilproblem/main/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for i in problems %}
    <h3>modify the problem with title as {{i.title }} </h3>
    

    <form action="" method="POST">
        {%csrf_token%}

        {{form.as_p}}
        <br>

    
    <input type="submit" value="modify" class="btn btn-secondary">
</form>

</body>
</html>



        



              
              
              
            







civilproblem/main/templates/view.html
{% extends 'base.html' %}

{% block th1 %}Title{%endblock %}
{% block th2 %}description<a>view</a>{%endblock %}
{% block th3 %} Post Date{%endblock %}
{% block th4 %}Posted by{%endblock %}
{% block th5 %}Location{%endblock %}
{% block th6 %}votes{%endblock %}

{% block th7 %}status{%endblock %}
{% block th8 %}Modify or delete  problem  {%endblock %}
{% block mytablebody %} 
    {% for i in problems  %}

        <tr>
            <th scope="row">{{i.title}}</th>
            <td>{{i.desc}}</td>
            <td>{{i.postdate}}</td>
            <td>{{i.postedby}}</td>
            <td>{{i.location}}</td>
            <td>{{i.votes}}</td>
            
            <td >
                {{i.status}}
                
                
            </td>
            <td>
                <a href="/modify/{{i.prob_id}}">Modify </a><br>
                <a href="/delete/{{i.prob_id}}">Delete </a>
            </td>
            
            

        </tr>




        
    {% endfor %}
{% endblock %}
{%block js %}

{% endblock %}




              
              
              
            







civilproblem/main/templates/welcome.html
{% extends 'base.html' %}

{% block title%} ADMIN PAGE {% endblock %}
{% block body %}
<h3>
------------------------------------------------WELCOME ADMIN----------------------------------------------------------

</h3>


{% endblock %}